# Generated by Django 4.2.7 on 2023-12-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userprofile_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userset",
            name="gender",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "unknown"),
                    ("MALE", "male"),
                    ("FEMALE", "female"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
    ]
